const PTL_DEMO_DATA = {
  open1: {
    success: true,
    game: "PTL",
    total_participants: 100,
    active_participants: 100,
    last_updated_at: "2026-09-21T10:06:47.109736+00:00",
    pagination: {
      count: 100,
      next: true,
      previous: false,
      current_page: 1,
      total_pages: 2,
      items_per_page: 50,
    },
    results: [
      {
        points: 7,
        previous_rank: 1,
        status: "advancing",
        rank: 1,
        rank_direction: "same",
        user_id: 7892,
        name: "Ishaan_Mehta084",
        matches_played: 3,
        match_record: {
          won: 2,
          drawn: 1,
          lost: 0,
        },
        record_label: "2W · 1D · 0L",
        total_pnl: 344.0,
        total_pnl_label: "+$344",
        total_pnl_direction: "up",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: 5,
        previous_rank: 2,
        status: "advancing",
        rank: 2,
        rank_direction: "same",
        user_id: 7821,
        name: "Aryan_Kulkarni013",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: 5,
        previous_rank: 3,
        status: "advancing",
        rank: 3,
        rank_direction: "same",
        user_id: 7825,
        name: "Diya_Kapoor017",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: 5,
        previous_rank: 4,
        status: "advancing",
        rank: 4,
        rank_direction: "same",
        user_id: 7831,
        name: "Riya_Gupta023",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: 5,
        previous_rank: 5,
        status: "eliminated",
        rank: 5,
        rank_direction: "same",
        user_id: 7876,
        name: "Saanvi_Nair068",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: 10000,
          label: "$10,000",
          finale_seat: false,
        },
      },
      {
        points: 5,
        previous_rank: 6,
        status: "eliminated",
        rank: 6,
        rank_direction: "same",
        user_id: 7879,
        name: "Myra_Bose071",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: 5,
        previous_rank: 7,
        status: "eliminated",
        rank: 7,
        rank_direction: "same",
        user_id: 7894,
        name: "Kabir_Singh086",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: 5,
        previous_rank: 8,
        status: "eliminated",
        rank: 8,
        rank_direction: "same",
        user_id: 7896,
        name: "Aryan_Nair088",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: 5,
        previous_rank: 9,
        status: "eliminated",
        rank: 9,
        rank_direction: "same",
        user_id: 7902,
        name: "Aadhya_Joshi094",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 2,
          lost: 0,
        },
        record_label: "1W · 2D · 0L",
        total_pnl: 0.0,
        total_pnl_label: "$0",
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: 4,
        previous_rank: 10,
        status: "eliminated",
        rank: 10,
        rank_direction: "same",
        user_id: 7823,
        name: "Vihaan_Patel015",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 1,
          lost: 1,
        },
        record_label: "1W · 1D · 1L",
        total_pnl: -120.0,
        total_pnl_label: "-$120",
        total_pnl_direction: "down",
        reward: {
          amount: 5000,
          label: "$5,000",
          finale_seat: false,
        },
      },
      {
        points: 4,
        previous_rank: 11,
        status: "eliminated",
        rank: 11,
        rank_direction: "same",
        user_id: 7850,
        name: "Rohan_Deshmukh042",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 1,
          lost: 1,
        },
        record_label: "1W · 1D · 1L",
        total_pnl: -180.0,
        total_pnl_label: "-$180",
        total_pnl_direction: "down",
        reward: {
          amount: 5000,
          label: "$5,000",
          finale_seat: false,
        },
      },
      {
        points: 3,
        previous_rank: 12,
        status: "eliminated",
        rank: 12,
        rank_direction: "same",
        user_id: 7907,
        name: "Ananya_Sharma099",
        matches_played: 3,
        match_record: {
          won: 1,
          drawn: 0,
          lost: 2,
        },
        record_label: "1W · 0D · 2L",
        total_pnl: -310.0,
        total_pnl_label: "-$310",
        total_pnl_direction: "down",
        reward: {
          amount: 3000,
          label: "$3,000",
          finale_seat: false,
        },
      },
    ],
  },

  open2: {
    success: true,
    game: "PTL",
    total_participants: 100,
    active_participants: 100,
    last_updated_at: "2026-09-21T10:06:47.109736+00:00",
    pagination: {
      count: 100,
      next: true,
      previous: false,
      current_page: 1,
      total_pages: 1,
      items_per_page: 50,
    },
    results: [
      {
        points: null,
        previous_rank: null,
        status: "advancing",
        rank: 1,
        rank_direction: "same",
        user_id: 8101,
        name: "Reyansh_Chopra055",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "advancing",
        rank: 2,
        rank_direction: "same",
        user_id: 8102,
        name: "Advait_Rao077",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "advancing",
        rank: 3,
        rank_direction: "same",
        user_id: 8103,
        name: "Tara_Menon031",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "advancing",
        rank: 4,
        rank_direction: "same",
        user_id: 8104,
        name: "Zayn_Malik882",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: null,
          label: "Up to $180,000",
          finale_seat: true,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "eliminated",
        rank: 5,
        rank_direction: "same",
        user_id: 8105,
        name: "Siddharth_Verma049",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: 10000,
          label: "$10,000",
          finale_seat: false,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "eliminated",
        rank: 6,
        rank_direction: "same",
        user_id: 8106,
        name: "Elena_Rostova112",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "eliminated",
        rank: 7,
        rank_direction: "same",
        user_id: 8107,
        name: "Lucas_Silva204",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "eliminated",
        rank: 8,
        rank_direction: "same",
        user_id: 8108,
        name: "Chloe_Dupont062",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "eliminated",
        rank: 9,
        rank_direction: "same",
        user_id: 8109,
        name: "Marcus_Vance301",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: 8000,
          label: "$8,000",
          finale_seat: false,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "eliminated",
        rank: 10,
        rank_direction: "same",
        user_id: 8110,
        name: "Kavya_Reddy019",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: 5000,
          label: "$5,000",
          finale_seat: false,
        },
      },
      {
        points: null,
        previous_rank: null,
        status: "eliminated",
        rank: 11,
        rank_direction: "same",
        user_id: 8111,
        name: "Oliver_Wright088",
        matches_played: null,
        match_record: {
          won: null,
          drawn: null,
          lost: null,
        },
        record_label: null,
        total_pnl: null,
        total_pnl_label: null,
        total_pnl_direction: "same",
        reward: {
          amount: 5000,
          label: "$5,000",
          finale_seat: false,
        },
      },
    ],
  },

  creator_league_2: {
    success: true,
    status: 200,
    message: "PTL Creator Division public leaderboard fetched.",
    data: {
      campaign_id: 10,
      campaign_name: "PTL Creator Division",
      stage_id: 14,
      status: "live",
      date_label: "31 Aug - 31 Dec",
      current_game_day: 4,
      total_game_days: 6,
      total_creators: 16,
      leaderboard: [
        {
          rank: 1,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11264,
          participant_id: 5292,
          user_id: 6631,
          // username: 'itsKatchii',
          // display_handle: '@itsKatchii',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Katchii",
          last_name: null,
          full_name: "itsKatchii",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 64700,
          supporters_label: "64,700 supporters",
          company: {
            id: 50,
            name: "Arteezy's Trading Co",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 50000,
            label: "$50,000",
            finale_seat: true,
          },
        },
        {
          rank: 2,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11265,
          participant_id: 5293,
          user_id: 6628,
          // username: 'Penta',
          // display_handle: '@Penta',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Penta",
          last_name: null,
          full_name: "Penta RP",
          image_url:
            "[https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg](https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg)",
          supporters: 240000,
          supporters_label: "240,000 supporters",
          company: {
            id: 51,
            name: "Ludwig's Ventures",
            image_url:
              "[https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg](https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 35000,
            label: "$35,000",
            finale_seat: true,
          },
        },
        {
          rank: 3,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11266,
          participant_id: 5294,
          user_id: 6629,
          // username: 'Tminnzy',
          // display_handle: '@Tminnzy',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Tminnzy",
          last_name: null,
          full_name: "Tminnzy",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 215000,
          supporters_label: "215,000 supporters",
          company: {
            id: 52,
            name: "Toast Trading Corp",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 25000,
            label: "$25,000",
            finale_seat: true,
          },
        },
        {
          rank: 4,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11267,
          participant_id: 5295,
          user_id: 6630,
          // username: 'Pikabooirl',
          // display_handle: '@Pikabooirl',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Charlie",
          last_name: null,
          full_name: "MoistCr1TiKaL",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 198500,
          supporters_label: "198,500 supporters",
          company: {
            id: 53,
            name: "Moist Esports Co",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 20000,
            label: "$20,000",
            finale_seat: true,
          },
        },
        {
          rank: 5,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11268,
          participant_id: 5296,
          user_id: 6638,
          // username: 'Awake',
          // display_handle: '@Awake',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Lily",
          last_name: null,
          full_name: "Lily Ki",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 185000,
          supporters_label: "185,000 supporters",
          company: {
            id: 54,
            name: "Lily Melody Group",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 18000,
            label: "$18,000",
            finale_seat: false,
          },
        },
        {
          rank: 6,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11269,
          participant_id: 5297,
          user_id: 6632,
          // username: 'Nemo',
          // display_handle: '@Nemo',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Dan",
          last_name: "Chou",
          full_name: "Dan Chou",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 72050,
          supporters_label: "72,050 supporters",
          company: {
            id: 55,
            name: "Frodan Tactics LLC",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 18000,
            label: "$18,000",
            finale_seat: false,
          },
        },
        {
          rank: 7,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11270,
          participant_id: 5298,
          user_id: 6635,
          // username: 'EsfandTV',
          // display_handle: '@EsfandTV',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Syanne",
          last_name: null,
          full_name: "Syanne",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 94100,
          supporters_label: "94,100 supporters",
          company: {
            id: 56,
            name: "Syanne Global",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 14000,
            label: "$14,000",
            finale_seat: false,
          },
        },
        {
          rank: 8,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11271,
          participant_id: 5299,
          user_id: 6642,
          // username: 'CooperTV',
          // display_handle: '@CooperTV',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Yiliang",
          last_name: "Peng",
          full_name: "Yiliang Peng",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 145550,
          supporters_label: "145,550 supporters",
          company: {
            id: 57,
            name: "Doublelift Ventures",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 14000,
            label: "$14,000",
            finale_seat: false,
          },
        },
        {
          rank: 9,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11272,
          participant_id: 5300,
          user_id: 6636,
          // username: 'Nagzz',
          // display_handle: '@Nagzz',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Pikaboo",
          last_name: null,
          full_name: "Pikabooirl",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 101450,
          supporters_label: "101,450 supporters",
          company: {
            id: 58,
            name: "Pikaboo Rogues",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 8000,
            label: "$8,000",
            finale_seat: false,
          },
        },
        {
          rank: 10,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11273,
          participant_id: 5301,
          user_id: 6633,
          // username: 'Frodan',
          // display_handle: '@Frodan',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Esfand",
          last_name: null,
          full_name: "EsfandTV",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 79400,
          supporters_label: "79,400 supporters",
          company: {
            id: 59,
            name: "Esfand Paladins Co",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 8000,
            label: "$8,000",
            finale_seat: false,
          },
        },
        {
          rank: 11,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11274,
          participant_id: 5302,
          user_id: 6644,
          // username: 'VarsityGaming',
          // display_handle: '@VarsityGaming',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Qiyu",
          last_name: "Zhou",
          full_name: "Qiyu Zhou",
          image_url:
            "[https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg](https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg)",
          supporters: 160250,
          supporters_label: "160,250 supporters",
          company: {
            id: 60,
            name: "Nemo Grandmasters",
            image_url:
              "[https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg](https://cdn.prod.website-files.com/679b064a680c614548672a06/6aab989b3017369152bf41e3_Nemo-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 8000,
            label: "$8,000",
            finale_seat: false,
          },
        },
        {
          rank: 12,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11275,
          participant_id: 5303,
          user_id: 6645,
          // username: 'Arteezy',
          // display_handle: '@Arteezy',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Penta",
          last_name: null,
          full_name: "Penta RP",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 167600,
          supporters_label: "167,600 supporters",
          company: {
            id: 61,
            name: "Penta Syndicate",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 8000,
            label: "$8,000",
            finale_seat: false,
          },
        },
        {
          rank: 13,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11276,
          participant_id: 5304,
          user_id: 6639,
          // username: 'Thijs',
          // display_handle: '@Thijs',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Thijs",
          last_name: "Molendijk",
          full_name: "Thijs Molendijk",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 123500,
          supporters_label: "123,500 supporters",
          company: {
            id: 62,
            name: "Thijs Hearthstone Co",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 6000,
            label: "$6,000",
            finale_seat: false,
          },
        },
        {
          rank: 14,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11277,
          participant_id: 5305,
          user_id: 6634,
          // username: 'Juliakins',
          // display_handle: '@Juliakins',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Varsity",
          last_name: null,
          full_name: "Varsity Gaming",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 86750,
          supporters_label: "86,750 supporters",
          company: {
            id: 63,
            name: "Varsity Tactical",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 6000,
            label: "$6,000",
            finale_seat: false,
          },
        },
        {
          rank: 15,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11278,
          participant_id: 5306,
          user_id: 6637,
          // username: 'Syanne',
          // display_handle: '@Syanne',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Tminnzy",
          last_name: null,
          full_name: "Tminnzy",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 108800,
          supporters_label: "108,800 supporters",
          company: {
            id: 64,
            name: "Tminnzy Apex Co",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 6000,
            label: "$6,000",
            finale_seat: false,
          },
        },
        {
          rank: 16,
          previous_rank: null,
          rank_direction: "same",
          stage_participant_id: 11279,
          participant_id: 5307,
          user_id: 6641,
          // username: 'Qojqva',
          // display_handle: '@Qojqva',
          username: "Coming Soon",
          display_handle: "Coming Soon",
          first_name: "Katchii",
          last_name: null,
          full_name: "itsKatchii",
          image_url:
            "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          supporters: 138200,
          supporters_label: "138,200 supporters",
          company: {
            id: 65,
            name: "Katchii Holdings",
            image_url:
              "[https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg](https://d33zacp7h639z8.cloudfront.net/ptl/premier-league/competitor/Arteezy-show.jpg)",
          },
          points: 0,
          matches_played: 0,
          match_record: {
            won: 0,
            drawn: 0,
            lost: 0,
            no_show: 0,
            bye: 0,
            scheduled: 0,
          },
          record_label: "-",
          total_pnl: 0.0,
          total_pnl_label: "0",
          total_pnl_direction: null,
          reward: {
            amount: 6000,
            label: "$6,000",
            finale_seat: false,
          },
        },
      ],
    },
  },

  creator_league_2_individual_data: {
    success: true,
    user: {
      id: 12345,
      username: "Kaito_Ishida",
      country: {
        code: "JP",
        name: "Japan",
        flag: "🇯🇵",
      },
      team: null,
      status: "finale",
      rank: 3,
      previous_rank: 2,
      points: 431,
      record: {
        wins: 4,
        draws: 0,
        losses: 1,
        display: "4W · 0D · 1L",
      },
      total_pnl: 35110,
      matches_played: 5,
      total_matches: 8,
    },
    current_match: {
      match_number: 6,
      total_matches: 8,
      status: "in_progress",
      status_label: "LIVE",
      user: {
        username: "BrettSimba",
        country: {
          code: "US",
          name: "United States",
          flag: "🇺🇸",
        },
        balance: 58847.32,
        pnl: 5230,
        trades: 20,
      },
      opponent: {
        username: "Meatman00",
        country: {
          code: "GB",
          name: "United Kingdom",
          flag: "🇬🇧",
        },
        balance: 52847.32,
        pnl: 677,
        trades: 0,
      },
    },
    match_history: [
      {
        match: "M6",
        opponent: "Meatman00",
        color: "blue",
        result: "in_progress",
        result_label: "In progress",
        user_final_balance: 58847,
        opponent_final_balance: 54294,
        points: 13,
      },
      {
        match: "M5",
        opponent: "RiverRun88",
        color: "purple",
        result: "won",
        result_label: "Won",
        user_final_balance: 56410,
        opponent_final_balance: 50120,
        points: 14,
      },
      {
        match: "M4",
        opponent: "ClaraVoss",
        color: "pink",
        result: "won",
        result_label: "Won",
        user_final_balance: 53980,
        opponent_final_balance: 49760,
        points: 13,
      },
      {
        match: "M3",
        opponent: "AlphaWaveJo",
        color: "green",
        result: "lost",
        result_label: "Lost",
        user_final_balance: 48220,
        opponent_final_balance: 52640,
        points: 6,
      },
      {
        match: "M2",
        opponent: "SilentTape",
        color: "yellow",
        result: "won",
        result_label: "Won",
        user_final_balance: 52110,
        opponent_final_balance: 47890,
        points: 12,
      },
      {
        match: "M1",
        opponent: "QuantMirage",
        color: "burgundy",
        result: "won",
        result_label: "Won",
        user_final_balance: 51040,
        opponent_final_balance: 48300,
        points: 11,
      },
    ],
  },
};

try {
  module.exports = PTL_DEMO_DATA;
} catch (e) {}
